apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: targeting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: 185796529499.dkr.ecr.us-east-1.amazonaws.com/togglemaster/targeting-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: targeting-service-config
            - secretRef:
                name: targeting-service-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: targeting
spec:
  type: ClusterIP
  selector:
    app: targeting-service
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-service-config
  namespace: targeting
data:
  PORT: "8003"
  AUTH_SERVICE_URL: "http://auth-service.auth.svc.cluster.local:8001"