apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: evaluation
data:
  PORT: "8004"
  FLAG_SERVICE_URL: "http://flag-service.flag.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service.targeting.svc.cluster.local:8003"
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/247641494065/toggle-events-queue"
  SERVICE_API_KEY: "tm_key_a8744f5c93611b3f4d30c9857b5c979312928e1d854a010e270dbd35fdbc986e"
