name: Terraform

on:
  pull_request:
    branches: [master]
    paths:
      - "terraform/**"
  push:
    branches: [master]
    paths:
      - "terraform/**"

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.6.6"
  AWS_REGION: us-east-1
  TF_STATE_BUCKET: togglemaster-tfstate-185796529499
  TF_LOCK_TABLE: terraform-lock

jobs:
  terraform:
    name: "Terraform (${{ matrix.env }})"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    strategy:
      matrix:
        env: [dev]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="dynamodb_table=$TF_LOCK_TABLE" -backend-config="region=$AWS_REGION"

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -var "environment=${{ matrix.env }}" \
            -var "auth_db_password=${{ secrets.AUTH_DB_PASSWORD }}" \
            -var "flags_db_password=${{ secrets.FLAGS_DB_PASSWORD }}" \
            -var "targeting_db_password=${{ secrets.TARGETING_DB_PASSWORD }}"
        continue-on-error: true

      # Aplica somente em push para master
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          terraform apply -auto-approve -no-color -var "environment=${{ matrix.env }}" \
            -var "auth_db_password=${{ secrets.AUTH_DB_PASSWORD }}" \
            -var "flags_db_password=${{ secrets.FLAGS_DB_PASSWORD }}" \
            -var "targeting_db_password=${{ secrets.TARGETING_DB_PASSWORD }}"